### ISSUE TITLE
jwhois.exe cannot start (0xc000007b)

### ISSUE THREAD

**Issue by LantosIstvan** [arizvisa/jwhois#1]
I installed MSYS2 64bit on my Windows 10 PC. I copied `jwhois.exe` into `C:\msys64\usr\bin` and `jwhois.conf` into `C:\msys64\etc`. Application dropping the following error when I try to run from cmd (`C:\msys64\usr\bin` is part of my PATH). If try to run with `start_shell.cmd` as the recommended shell, application finishing to run without any console output.

**Comment by arizvisa** [comment]
I haven't tested anything against windows 10, so I can't be 100% sure..but what's the error? it might display something in the event viewer. Error 0xc000007b means bad image, so that would mean it's built incorrectly. You might be able to identify the issue by running dependency viewer against the binary as well.

also, this isn't the posix jwhois but rather a windows variation of it that's designed for when you don't want to install all of msys on a box. If you're running msys, I highly recommend using the original jwhois. As an example, the jwhois.conf and jwhois.exe from this repository need to be in the same directory as it's designed to be used from the cmd.exe or powershell.exe prompt.

**Comment by LantosIstvan** [comment]
I use MSYS2. I didn't found any jwhois package with `$ pacman -Ss jwhois`. If it's part of MSYS2, can you give me a package name?

**Comment by arizvisa** [comment]
GNU has a list of mirrors at `https://www.gnu.org/prep/ftp.html`. You can download jwhois from one of them such as `ftp://ftp.gnu.org/pub/gnu/jwhois/`

The latest is `ftp://ftp.gnu.org/pub/gnu/jwhois/jwhois-4.0.tar.gz`.

After you extract it, you can then do the standard `./configure && make install` dance and you should be good to go.

**Comment by DJviolin** [comment]
I got the following error when I try to make it with MSYS2:

```bash
Lanti@LANTI-PC MINGW64 ~/crunch-3.6
$ make
Building binary...
/usr/bin/gcc  -pthread -Wall -pedantic -std=c11  undefined crunch.c -lm  -o crunch
gcc: error: undefined: No such file or directory
make: *** [Makefile:75: crunch] Error 1
```
